[versions]
kotlin = "2.0.0"
itext = "8.0.5"

[libraries]
itext-kernel = { group = "com.itextpdf", name = "kernel", version.ref = "itext" }
itext-io = { group = "com.itextpdf", name = "io", version.ref = "itext" }
itext-layout = { group = "com.itextpdf", name = "layout", version.ref = "itext" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }